apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "campanhas-api"
        metrics_path: /metrics
        static_configs:
          - targets: ["campanhas-api-service:8080"]