apiVersion: apps/v1
kind: Deployment

metadata:
  name: donation-worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: donation-worker

  template:
    metadata:
      labels:
        app: donation-worker

    spec:
      containers:
        - name: donation-worker

          image: vitordietrich/processador-doacoes:latest

          imagePullPolicy: Always

          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver-service;Database=DB_Campanhas;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

            - name: RabbitMQ__Host
              value: rabbitmq-service

            - name: RabbitMQ__Username
              value: guest

            - name: RabbitMQ__Password
              value: guest

            - name: RabbitMQ__DonationQueue
              value: donations